apiVersion: v1
kind: Service
metadata:
  labels:
    role: passwordapi
  name: passwordapi
spec:
  ports:
  - name: passwordapi
    port: 8083
  selector:
    role: passwordapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: passwordapi
  name: passwordapi
spec:
  replicas: 1
  selector:
    matchLabels:
      role: passwordapi
  template:
    metadata:
      labels:
        role: passwordapi
      name: passwordapi
    spec:
      containers:
      - envFrom:
        image: tamatping/passwordapi:latest
        name: passwordapi
        ports:
        - containerPort: 8083
        resources:
          limits:
            cpu: "1"
            memory: 1.5Gi
          requests:
            cpu: "1"
            memory: 1.5Gi
